<?php


namespace app\admin\controller\v1;


use think\facade\Request;
use think\Validate;

class Auth extends BaseController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //查看权限
    public function index(){

    }

    //添加权限
    public function addAuth(){
        $data = Request::instance()->post();
        $validate = Validate('Auth');
        if (!$validate->check($data)) {
            return returnJson(getMsg($validate->getError()),$validate->getError());
        }
    }
}