<?php

namespace app\admin\controller\v1;

class Index extends BaseController{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        echo 3244;
    }
}